ls:
  .js: kebab-case
  .ts: kebab-case
  .tsx: kebab-case
  .css: kebab-case
  .html: kebab-case
  .json: kebab-case
  .md: kebab-case
  .yaml: kebab-case

ignore:
  - .git
  - .github
  - .turbo
  - .vscode
  - node_modules
  - '**/node_modules'
  - dist
  - '**/dist'
  - coverage
  - .DS_Store
  - pnpm-lock.yaml
  - pnpm-workspace.yaml
  - README.md
  - '**/README.md'
  - LICENSE
  - Dockerfile
  - eslint.config.mjs
  - eslint.config.js
  - '**/vite.config.ts'
  - '**/vite.config.js'
  - '**/playwright.config.ts'
  - knip.json
  - turbo.json
  - '**/tsconfig.json'
  - '**/tsconfig.node.json'
  - '**/tsconfig.app.json'
  - requirements.spec.md
  - implementation.md
